POST  http://localhost:3003/api/blogs
Content-Type:  application/json

{
    "title": "Kuuma linja",
    "author": "Maria",
    "url": "maria.maria.fi",
    "likes": 42,
    "userId": "5d70dad132c1303d5462f460"
}